Feature/43 unit test
planimation/backend pull request #45
Opened 2020-10-16 01:10 UTC by JamieYuu

Added unit test feature to the project

2020-10-21 06:15 UTC, nirlipo requested changes
Thanks for the PR!

Besides the comments in the files, I have 2 more questions:

 - Should we move the test folder out of app?
 - Can you group the input files into different folders?

Thanks!

2020-10-21 06:15 UTC, nirlipo commented on server/app/unit_test/README.md
> +```
When it runs, can it give you some output messages of the tests it passed?

Why didn't we use django.tests?

2020-10-21 06:15 UTC, nirlipo commented on server/app/unit_test/test_cases.py
> +    def test_visitall(self):
add comments to the functions please. What is being tested in visitall?

2020-10-21 06:15 UTC, nirlipo commented on server/app/unit_test/test_cases.py
> +        self.assertTrue(filecmp.cmp(os.path.abspath(os.path.dirname(__file__) + '/../unit_test/' + 'test.vfg'), os.path.abspath(os.path.dirname(__file__) + '/../unit_test/' + 'expect_output.vfg'), sh
Shouldn't be an error message string that gives information about which part of the test failed? see this example: https://github.com/cgoldberg/python-unittest-tutorial

2020-10-26 06:03 UTC, JamieYuu commented
Hi @nirlipo , sorry for the late response, I was focusing on the planning-as-service project and forgot to check the messages here. I've made a few changes to the unit test branch according to your comments. 

For the django.test, we found the document says
> Django’s unit tests use a Python standard library module: unittest

From a functional point of view, using Django.test is the same as using the Python unittest module directly. So we think just using the Python unittest module would be more light and easy to use, and won't cause any potential conflict with the existing features.
We are looking forward to your reply, thank you for your time!

2020-10-27 09:53 UTC, nirlipo requested changes
Thanks for the changes. Please update the output in the Readme and we are ready to merge!

2020-10-27 09:53 UTC, nirlipo commented on server/unit_test/README.md
> +Ran 8 tests in 1.967s
Can you update the output of the new test_cases.py run?

2020-10-29 11:07 UTC, nirlipo approved these changes
Thanks!

2020-10-29 11:07 UTC, nirlipo commented
Please let me know how to include this on the travis pipeline!

2020-10-29 23:01 UTC, merged